version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  deploy_docs:
    name: Deploying Docs
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npx s deploy
      - run: npx s sync staging


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          required:
            - deploy
