version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  deploy:
    name: Deploying Docs
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npx s deploy
      - run: npx s hosting config staging --cname humanimpact.hacklag.org
      - run: npx s hosting sync staging


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
